# 线上配置文件 - Railway Production
server:
  port: ${PORT:10000}
  address: 0.0.0.0
  servlet:
    context-path: /api
spring:
  # PostgreSQL配置 - Railway自动提供
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${DATABASE_URL}
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:}
    hikari:
      maximum-pool-size: 5
      minimum-idle: 2
  # Redis 配置 - 暂时注释（Railway不提供）
  # redis:
  #   database: 1
  #   host: localhost
  #   port: 6379
  #   timeout: 5000
  #   password: 123456
  # Elasticsearch 配置 - 暂时注释（Railway不提供）
  # elasticsearch:
  #   uris: http://localhost:9200
  #   username: root
  #   password: 123456
mybatis-plus:
  configuration:
    # 生产环境关闭日志
    log-impl: ''
# 接口文档配置
knife4j:
  basic:
    enable: true
    username: root
    password: 123456
